version: '3'
services:  # each service is a container
  my-node-container:
    build: .
    ports:
      - "2000:4000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=4000
    # env_file:
    #   - ./.env